// Generated by nestjs-docfy — edit freely, use --force to merge new methods
import { docs } from 'nestjs-docfy';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiBody,
} from '@nestjs/swagger';
import { UsersController } from './users.controller';
import { CreateUserDto } from './dto/create-user.dto';
import { FindUserByEmailDto } from './dto/find-user-by-email.dto';
import { CreateUserOutput } from './use-cases/create-user.use-case';
import { FindUserByIdOutput } from './use-cases/find-user-by-id.use-case';
import { FindUserByEmailOutput } from './use-cases/find-user-by-email.use-case';

docs(UsersController, {
  classDecorators: [ApiTags('Users')],
  methods: {
    create: [
      ApiOperation({
        summary: 'Create a new user',
        description: 'Registers a new user account with email and password',
      }),
      ApiBody({ type: CreateUserDto }),
      ApiResponse({
        status: 201,
        description: 'User created successfully',
        type: CreateUserOutput,
        example: {
          id: '3b0c6501-e793-4bb6-ab20-549371276187',
          email: 'user@example.com',
          preferredDisplayMode: 'TRANSLATED',
          createdAt: '2026-06-16T13:45:00.000Z',
          updatedAt: '2026-06-16T13:45:00.000Z',
        },
      }),
      ApiResponse({
        status: 409,
        description: 'Email already in use',
        example: { message: 'Email already in use', statusCode: 409 },
      }),
      ApiResponse({
        status: 400,
        description: 'Bad request - validation error',
      }),
    ],

    findUserById: [
      ApiOperation({
        summary: 'Get user by ID',
        description: 'Retrieves user information by UUID',
      }),
      ApiParam({
        name: 'id',
        type: String,
        description: 'User UUID',
        example: '3b0c6501-e793-4bb6-ab20-549371276187',
      }),
      ApiResponse({
        status: 200,
        description: 'User found',
        type: FindUserByIdOutput,
        example: {
          id: '3b0c6501-e793-4bb6-ab20-549371276187',
          email: 'user@example.com',
          preferredDisplayMode: 'TRANSLATED',
          createdAt: '2026-06-16T13:45:00.000Z',
          updatedAt: '2026-06-16T13:45:00.000Z',
        },
      }),
      ApiResponse({
        status: 404,
        description: 'User not found',
        example: { message: 'User not found', statusCode: 404 },
      }),
      ApiResponse({
        status: 400,
        description: 'Invalid UUID format',
      }),
    ],

    findUserByEmail: [
      ApiOperation({
        summary: 'Get user by email',
        description: 'Retrieves user information by email address',
      }),
      ApiBody({ type: FindUserByEmailDto }),
      ApiResponse({
        status: 200,
        description: 'User found',
        type: FindUserByEmailOutput,
        example: {
          id: '3b0c6501-e793-4bb6-ab20-549371276187',
          email: 'user@example.com',
          preferredDisplayMode: 'TRANSLATED',
          createdAt: '2026-06-16T13:45:00.000Z',
          updatedAt: '2026-06-16T13:45:00.000Z',
        },
      }),
      ApiResponse({
        status: 404,
        description: 'User not found',
        example: { message: 'User not found', statusCode: 404 },
      }),
      ApiResponse({
        status: 400,
        description: 'Bad request - validation error',
      }),
    ],
  },
});
