// Generated by nestjs-docfy — edit freely, use --force to merge new methods
import { docs } from 'nestjs-docfy';
import { ApiTags, ApiOperation, ApiResponse, ApiParam, ApiBody } from '@nestjs/swagger';
import { UsersController } from './users.controller';
import { CreateUserOutput } from './use-cases/create-user.use-case';
import { FindUserByIdOutput } from './use-cases/find-user-by-id.use-case';
import { FindUserByEmailOutput } from './use-cases/find-user-by-email.use-case';

docs(UsersController, {
  classDecorators: [
    ApiTags('users'),
  ],
  methods: {
  // POST  → async create(dto: CreateUserDto): Promise<CreateUserOutput>
  create: [
    ApiOperation({ summary: 'Create' }),
    ApiBody({ schema: {
        type: 'object',
        properties: {
          email: {
            type: 'string',
            format: 'email',
            minLength: 3,
            maxLength: 80,
          },
          password: {
            type: 'string',
            minLength: 6,
            maxLength: 32,
          },
        },
        required: ['email', 'password'],
      } }),
    ApiResponse({ status: 201, description: 'Created', type: CreateUserOutput }),
    ApiResponse({ status: 400, description: 'Bad Request' }),
  ],

  // GET /:id → async findUserById(id: string): Promise<FindUserByIdOutput>
  findUserById: [
    ApiOperation({ summary: 'Find user by id' }),
    ApiParam({ name: 'id', type: String }),
    ApiResponse({ status: 200, description: 'OK', type: FindUserByIdOutput }),
  ],

  // POST /email → async findUserByEmail(dto: FindUserByEmailDto): Promise<FindUserByEmailOutput>
  findUserByEmail: [
    ApiOperation({ summary: 'Find user by email' }),
    ApiBody({ schema: {
        type: 'object',
        properties: {
          email: {
            type: 'string',
            format: 'email',
          },
        },
        required: ['email'],
      } }),
    ApiResponse({ status: 201, description: 'Created', type: FindUserByEmailOutput }),
    ApiResponse({ status: 400, description: 'Bad Request' }),
  ],
  },
});
