// Generated by nestjs-docfy — edit freely, use --force to merge new methods
import { docs } from 'nestjs-docfy';
import { ApiTags, ApiOperation, ApiResponse, ApiBody } from '@nestjs/swagger';
import { AuthController } from './auth.controller';
import { TokenDto } from './dto/token.dto';

docs(AuthController, {
  classDecorators: [
    ApiTags('auth'),
  ],
  methods: {
  // POST /login → async login(dto: LoginDto): Promise<TokenDto>
  login: [
    ApiOperation({ summary: 'Login' }),
    ApiBody({ schema: {
        type: 'object',
        properties: {
          email: {
            type: 'string',
            format: 'email',
          },
          password: {
            type: 'string',
            minLength: 6,
          },
        },
        required: ['email', 'password'],
      } }),
    ApiResponse({ status: 201, description: 'Created', type: TokenDto }),
    ApiResponse({ status: 400, description: 'Bad Request' }),
  ],

  // POST /refresh → async refresh(userId: string, refreshToken: string): Promise<TokenDto>
  refresh: [
    ApiOperation({ summary: 'Refresh' }),
    ApiResponse({ status: 201, description: 'Created', type: TokenDto }),
  ],

  // POST /logout → async logout(userId: string): Promise<{ message: string; }>
  logout: [
    ApiOperation({ summary: 'Logout' }),
    ApiResponse({ status: 201, description: 'Created' }),
  ],
  },
});
